# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    jobs:
      test:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
          - name: Check out repository code
            uses: actions/checkout@v2

          # Setup Python (faster than using Python container)
          - name: Setup Python
            uses: actions/setup-python@v2
            with:
              python-version: "3.8"
              cache: 'pip'
          - run: pip install -r requirements.txt
          - run: pytest